export enum ServicesString {
  assets = 'assets',
  users = 'users',
  roles = 'roles',
  permissions = 'permissions',
  permissionAssign = 'permissions/assign',
  permissionRevoke = 'permissions/revoke',
  me = 'me',
  passChange= 'me/password',
  logout = 'logout',
  datos = 'datos',
  empleados = 'empleados',
  horarios = 'horarios',
  puestos = 'puestos',
  registros = 'registros',
  salarios = 'salarios',
  tipospermisotrabajo = 'tipospermisotrabajo',
  permisostrabajo = 'permisostrabajo',
  authToken = 'token',
  authRefrehToken = 'token/refresh',
}
